### PR TITLE
Revisions to README for subspecs

### PR DESCRIPTION
**Pull request by benron**
Makes clear how to avoid including HealthKit and Pass capabilities, which can cause app store rejections if included and not used.

### CODE REVIEW

**Comment by benron** [comment]
See https://guides.cocoapods.org/syntax/podspec.html#tab_subspec

**Comment by mcmurrym** [comment]
This is good, but what if you want the core with HealthKit and not PassKit or PassKit and not HealthKit, these changes don't seem to reflect how to use the core and one of the sub specs.

**Comment by benron** [comment]
ok, I'll adjust for those scenarios

**Comment by mcmurrym** [comment]
@benron I'd love it if we could get these changes taken care of.

**Comment by benron** [comment]
sorry for the delay!

**Pull request merged**
