### PR TITLE
Refactored CalendarCapability into its own podspec.

### PR DESCRIPTION
**Pull request by axello**
I have no experience with *testing* the podspec, apart from using it. So please use caution.

### CODE REVIEW

**Comment by sean7512** [comment]
Any updates/timeframe on getting this merged in and released?

**Comment by mcmurrym** [comment]
@axello I am reviewing this now, will you update the readme for this pull request to explain the Calendar subspec like the other subspaces are. Thanks

**Comment by axello** [comment]
Done!

**Comment by mcmurrym** [comment]
merged and updated pod pushed

**Pull request merged**
