### PR TITLE
https://github.com/pluralsight/PSOperations/issues/53

### PR DESCRIPTION
**Pull request by purrrminator**
https://github.com/pluralsight/PSOperations/issues/53
There was a problem with serial operation queue and operations without any conditions, added to the queue synchronously.

### CODE REVIEW

**Comment by mcmurrym** [comment]
@purrrminator please rebase this branch from master. I had to switch the build to use xcodebuild over xctool in order to get the build working again.

**Comment by purrrminator** [comment]
@mcmurrym not sure if I've done it right...

**Comment by mcmurrym** [comment]
@purrrminator merge is fine. Thanks.

**Comment by mcmurrym** [comment]
We will be going with #63 for this fix. Thank you for you help!

**Pull request closed without merging**
