### PR TITLE
Enabling 'Allow app extension API Only'

### PR DESCRIPTION
**Pull request by Visorox**
This is needed to silence warnings from app extensions linking to this library.

Turning on this prevents the project from building if it uses any none app extension API.

### CODE REVIEW

**Comment by MarkQSchultz** [comment]
@Visorox: not sure if you saw, but looks like the build failed

**Comment by Visorox** [comment]
Yeah. Im not quite sure what's gone wrong here. It builds locally and the unit tests are successful. The error is ```  [Info] Collecting info for testables... (7310 ms)
  run-test PSOperationsTests.xctest (iphonesimulator9.0, iPhone 4s, logic-test)
2015-09-16 10:26:54.425 xctool[600:3266] *** Assertion failure in -[OCUnitIOSLogicTestRunner testEnvironmentWithSpecifiedTestConfiguration], /tmp/xctool20150824-26666-g0ve6w/xctool-0.2.5/xctool/xctool/OCUnitTestRunner.m:333
2015-09-16 10:26:54.447 xctool[600:3266] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'XCTestConfiguration isn't available'```

I'm wondering if Travis was hiccuping and it just needs to run it again.

**Comment by Visorox** [comment]
So Travis uses xctool and there appears to be issues with it and xcode 7 https://github.com/facebook/xctool/issues/528

**Comment by Visorox** [comment]
I see it failed again. Im a bit stumped

**Comment by Visorox** [comment]
So it's failing with this command 

```
The command "xctool -project PSOperations.xcodeproj -scheme PSOperations -sdk iphonesimulator build test" exited with 134.
```

but when I run that locally it works fine. I see the master branch is also failing so I think there's something screwed with Travis

**Comment by Visorox** [comment]
Okay if this blog post from Travis is anything to go by they're still rolling with xctool 0.25 http://blog.travis-ci.com/2015-09-09-xcode7-gm/

Looking at the xctool releases 0.26 adds xcode 7 support. https://github.com/facebook/xctool/releases

I'm gonna badger travis-ci on twitter

**Comment by Visorox** [comment]
They updated to xctool 0.26 this morning so I restarted the build and it was successful. LGTM

**Pull request merged**
