### PR TITLE
Added Podspec file

### PR DESCRIPTION
**Pull request by gblotter**
First, let me say Thank You!  I love the concept; my dev team had thought to do the same thing.

Would you consider making it a **Cocoapod** and/or allowing for **Carthage** integration?

For **Cocoapod** ask, I'm including a candidate for a podspec, which should you guys approve, would only require you to tag and then publish via [cocoapods.org](https://cocoapods.org/). The pod spec *should* be ready to go, but again you'd need to tag... which brings me to my next ask:  
**Carthage**. I believe all you need to do is tag your repo so that Carthage has something to pull against. (I'm still new to the Carthage scene).  

If I'm totally off base, I apologize.  Thanks again!

### CODE REVIEW

**Comment by MarkQSchultz** [comment]
According to the [cartfile documentation](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfile), there isn't really anything special we need to do (other than what was fixed in #2) to support Carthage. You can use branch name, tag, or commit in your `cartfile` to checkout specific versions.

**Comment by MarkQSchultz** [comment]
Have you linted the `podspec` @gblotter?

**Comment by gblotter** [comment]
@MarkQSchultz - Yessir.  I'm fixing the spelling error and will commit in a sec.

**Comment by gblotter** [comment]
As for the Cartfile... I tried it earlier and neglected to specify a branch name, assuming it would default to master.  It failed the `carthage update`, but I believe you're right.  I'll look into specifying the branch.  Thx

**Comment by MarkQSchultz** [comment]
Also, if we add versioning and/or tags for cocoa pods, you could use the same tags for carthage.

**Comment by gblotter** [comment]
Exactly.

**Comment by markcleonard** [comment]
I agree that version tags should be added to better support carthage.

**Comment by gblotter** [comment]
I noticed you guys merged the PR... what are your plans for publishing the pod to Cocoapods.org?

**Comment by MarkQSchultz** [comment]
We'll get to it in the next day or two. My proposal (please give feedback) is that our versioning will match Swift's versioning. This way it will always be easy to know which version of our framework you will want to use. Any changes not related to Swift will be in patch versions (e.g. 2.0.x). Are you wanting this done by a certain day/time @gblotter?

**Comment by gblotter** [comment]
That sounds good to me... that makes it really easy to specify versioning in the cocoa pods... i.e. ~2.0.0, which will grab all versions of 2.0.x.  

The only downside is the management on your part of testing the different releases that come out w/ Swift in the future that may or may not break the code.  eg: Swift 2.1 is in beta... assume that it doesn't break the code in any way... you'll have to remember to up the version tag when it goes public, even if there weren't any code changes to the repository.

Also, how does this handle showing backwards compatibility?  Or do you care?

Anyway.. your timeline is fine.  I can point to my local fork until you have time to publish it.

Thanks again!

**Comment by MarkQSchultz** [comment]
We (so far) have been ok updating the code. Since we're using the framework in our project, we have to update it every time there is a new release of Xcode anyway. I do see what you're saying though that when there are no changes we may not remember to bump the version. Hmmmmm.

And as far as backwards compatibility, those on earlier versions of Swift would just have to remain on earlier versions of the framework. It's too difficult to maintain backwards compatibility with a language changing this frequently. We have to choose either backwards compatibility, or keeping up to date with the language. I'd rather do the latter.

**Comment by gblotter** [comment]
You guys get a chance to publish this pod yet?

**Pull request merged**
