### PR TITLE
Moved LocationCapability and LocationOperation into their own podspec

### PR DESCRIPTION
**Pull request by gregoiredx**
When trying to submit an App depending on PSOperations/Core to the AppStore, Apple is complaining about missing Info.plist keys "NSLocationAlwaysUsageDescription" and "NSLocationWhenInUseUsageDescription". 
This comes from the use of CLLocationManager#requestAlwaysAuthorization  and CLLocationManager#requestWhenInUseAuthorization (see [apple doc](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW18)).
This commit moves files depending on CoreLocation to a dedicated Pod "PSOperations/Location".
[Related issue](https://github.com/pluralsight/PSOperations/issues/109)

### CODE REVIEW

**Comment by mcmurrym** [comment]
This looks great. I'll try and get it merged and the pod spec updated and published soon.

**Comment by gregoiredx** [comment]
Ok perfect. Have you planned a tag/release soon?

**Comment by mcmurrym** [comment]
working on 2 releases now, one with this change and thing the next one which will move the project to swift 4.1

**Comment by mcmurrym** [comment]
PSOperations pod version 4.0.2 is out it includes this change

**Comment by gregoiredx** [comment]
Nice, thank you.

**Pull request merged**
